### ISSUE TITLE
How can I use a custom Arco theme?

### ISSUE THREAD

**Issue by kustone** [wiidede/arco-design-nuxt-module#1]
First of all, thank you very much for this project. When building the project, I found that Nuxt3 does not seem to recognize my custom theme from Arco Design Lab through plugins and nuxt.config.json. Even after importing the theme styles, it still defaults to the default Arco theme.

https://arco.design/themes

**Comment by kustone** [comment]
It was my mistake. The issue was that I mistakenly cached an older version of the theme during installation. However, I have already resolved the problem.

**Comment by wiidede** [comment]
Thank you for bringing this to my attention.

I add the `theme` config. Now, we can use `theme` to import theme style. Alternatively, you can set the `importStyle` to false and add css to nuxt.config.ts.
