### ISSUE TITLE
在SSR模式下，样式会延迟加载

### ISSUE THREAD

**Issue by lhlyu** [wiidede/arco-design-nuxt-module#10]
下面是效果图，我刷新页面后，布局开始是没有样式的，过了一下才正常:

![CPT2405121509-882x676](https://github.com/wiidede/arco-design-nuxt-module/assets/41979509/107e7595-f38d-4190-9246-ecc910396f85)

这里有个我写的一个简单[示例代码](https://stackblitz.com/edit/github-udycmk?file=app.vue)

**Comment by wiidede** [comment]
不是样式延迟加载，而是ssr模式编译的页面是竖着的（has-slider类没有带上去），可以在layout组件上加上has-sider属性。（感谢提醒，我也更新了一下本项目的playground）

> https://arco.design/vue/component/layout#API

| 参数名    | 描述                                                         | 类型      | 默认值  |
| :-------- | :----------------------------------------------------------- | :-------- | :------ |
| has-sider | 表示子元素里有 Sider，一般不用指定。可用于服务端渲染时避免样式闪动 | `boolean` | `false` |

**Comment by lhlyu** [comment]
😓我的问题，没想到还有对nuxt的特殊处理
