### ISSUE TITLE
AMessage 无法使用

### ISSUE THREAD

**Issue by Liripo** [wiidede/arco-design-nuxt-module#12]
```js
function handleMessage() {
  AMessage.success('This is an info message')
}
```
增加上面的代码就会报下面的错误，删除就可以：
![image](https://github.com/user-attachments/assets/4a9f1a19-823b-4787-aa6c-fc5de1be91ef)

**Comment by wiidede** [comment]
我无法复现，请提供最小实现

顺带一提，你的package.json中，是否有安装@arco-design/web-vue

**Comment by Liripo** [comment]
加了安装命令之后可以了。
```bash
pnpm install --save-dev @arco-design/web-vue
```
文档没有提示安装@arco-design/web-vue，以为不用装就可以了。 @wiidede

**Comment by wiidede** [comment]
我写了，setup第一条就有，我有空搞的明显点吧，这个问题你是第二个issue了
