### ISSUE TITLE
全局方法及类型声明不完善

### ISSUE THREAD

**Issue by eevaery** [wiidede/arco-design-nuxt-module#4]
从 `.next/types/import.d.ts` 得知可用全局方法有
- Message
- Notification
- useFormItem

但它们没有完善的类型声明，例如：
![CleanShot 2023-11-16 at 19 49 14](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/e0b163a9-f439-4af0-843d-b646f9418f0a)

另外存在未支持方法，例如：
![CleanShot 2023-11-16 at 19 50 22](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/70cee93f-0d30-4cf5-8ded-4d480d2127b5)

**Comment by wiidede** [comment]
我稍微看了一下，它这个类型现在是这样定义的
```ts
declare global {
  const AMessage: typeof import('../../../node_modules/.pnpm/@arco-design+web-vue@2.53.2_vue@3.3.8/node_modules/@arco-design/web-vue/lib/index')['Message']
  const ANotification: typeof import('../../../node_modules/.pnpm/@arco-design+web-vue@2.53.2_vue@3.3.8/node_modules/@arco-design/web-vue/lib/index')['Notification']
}
```

重要的是它的定义是从`/@arco-design/web-vue/lib/index`引入的，那可能确实有问题

我代码写的是从`@arco-design/web-vue`引入的这些东西，但是不知道nuxt这边的类型定义取的是main(`/@arco-design/web-vue/lib/index`)
如果我代码写成从`@arco-design/web-vue/es`引入，就没有问题了，但是总觉得没必要指定es
我可能会抽空去了解一下nuxt这边怎么回事，因为以前这里是没问题的

**Comment by eevaery** [comment]
> 我稍微看了一下，它这个类型现在是这样定义的
> 
> ```ts
> declare global {
>   const AMessage: typeof import('../../../node_modules/.pnpm/@arco-design+web-vue@2.53.2_vue@3.3.8/node_modules/@arco-design/web-vue/lib/index')['Message']
>   const ANotification: typeof import('../../../node_modules/.pnpm/@arco-design+web-vue@2.53.2_vue@3.3.8/node_modules/@arco-design/web-vue/lib/index')['Notification']
> }
> ```
> 
> 重要的是它的定义是从`/@arco-design/web-vue/lib/index`引入的，那可能确实有问题
> 
> 我代码写的是从`@arco-design/web-vue`引入的这些东西，但是不知道nuxt这边的类型定义取的是main(`/@arco-design/web-vue/lib/index`) 如果我代码写成从`@arco-design/web-vue/es`引入，就没有问题了，但是总觉得没必要指定es 我可能会抽空去了解一下nuxt这边怎么回事，因为以前这里是没问题的

理解 👍
还存在一个问题是 tsx 无类型支持
![CleanShot 2023-11-17 at 23 31 05@2x](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/766576d3-fe7e-4894-bb1a-dbdabb1b51f2)

**Comment by wiidede** [comment]
我看了一下，arco-design/vue没有指定exports，也没指定module，mlly resolvePath的结果是/lib，我在mlly提了一个issue，https://github.com/unjs/mlly/issues/206 （可能单纯就是arco-design的锅🥹）

但我还是改了一下，现在所有引入都会指定从/es引入（可配置）。虽然我很不负责任的没测从lib引入，我不知道会不会真有人用cjs

**Comment by yveeven** [comment]
我也这样觉得，我想 mlly 的结果可能是基于 ECMAScript 的，此问题应当属于 arco-design
也谢谢你做出的优化

**Comment by eevaery** [comment]
首先感谢你做出的优化
另外我在查看 arco-degisn/web-vue 时是发现了一些情况，不知道它对你是否有帮助
![CleanShot 2023-11-19 at 02 21 31@2x](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/26017e61-88a9-42ee-8dc7-c4d8e6305235)

**Comment by pi0** [comment]
https://github.com/unjs/mlly/issues/206#issuecomment-1817946385 (let me know if could help & sorry i couldn't help in your language)

**Comment by wiidede** [comment]
> [unjs/mlly#206 (comment)](https://github.com/unjs/mlly/issues/206#issuecomment-1817946385) (let me know if could help & sorry i couldn't help in your language)

Thank you very much. This is because in this module. I add some imports to nuxt's auto-imports. Like `import Message from '@arco-design/web-vue'`.

And in nuxt. It will generate `types/imports.d.ts` by resolve the path of `from`

https://github.com/nuxt/nuxt/blob/7cce0ef6e6e0733b5bdee368e8015d955623df19/packages/nuxt/src/imports/module.ts#L153

And the result in this situation is: 

```ts
declare global {
  const Message: typeof import('../../../node_modules/.pnpm/@arco-design+web-vue@2.53.2_vue@3.3.8/node_modules/@arco-design/web-vue/lib/index')['Message']
}
```

Because arco-design do not have a `exports` field in package.json. mlly return the path of main(`@arco-design/web-vue/lib`). And arco-design does not provide a d.ts file in lib folder(😂). So the type of Message is any.

Maybe arco-design is a little confused. So in this module, I made it clear where to import from(A config to specify import from lib or es).

**Comment by wiidede** [comment]
@yveeven 

- import类型现在有了
- Modal也支持了自动引入，如果还需要其他特性，pr welcom
- tsx的问题，你确认一下，是不是只有这个模块自动引入的组件有类型问题，如果是，请提供最小复现

**Comment by eevaery** [comment]
tsx 的问题我想可以不用考虑了，自我觉得使用方式不常规，但是可能存在一个情况是 Notification 这个类型的识别会定位到 vscode 的内置类型，不知道你是否有这个情况
![CleanShot 2023-11-20 at 23 54 13@2x](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/d5abcc8c-60c8-4f71-a694-ab10b6cac356)
![CleanShot 2023-11-20 at 23 59 54@2x](https://github.com/wiidede/arco-design-nuxt-module/assets/76424723/4dce7065-c9c3-40dc-8150-5563b304e6f0)

**Comment by eevaery** [comment]
目前我的处理方式是设定 import prefix 来避免重复

**Comment by wiidede** [comment]
> 目前我的处理方式是设定 import prefix 来避免重复

我暂时也是这么做的，而且类型的优先级，不是这个module能控制的

**Comment by eevaery** [comment]
👌
